// 'use client'
// import Head from 'next/head';
// import React from 'react';
// import Slider from 'react-slick';
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
// import SliderCard from '../SliderCard/SliderCard';

// export default function Featured() {
//   const settings = {
//     dots: true,
//     infinite: true,
//     speed: 500,
//     slidesToShow: 5,
//     slidesToScroll: 1,
//     autoplay: true,
//     autoplaySpeed: 3000,
//     responsive: [
//       {
//         breakpoint: 1024,
//         settings: {
//           slidesToShow: 3,
//           slidesToScroll: 1,
//           infinite: true,
//           dots: true,
//         }
//       },
//       {
//         breakpoint: 768,
//         settings: {
//           slidesToShow: 2,
//           slidesToScroll: 1,
//           infinite: true,
//           dots: true,
//         }
//       },
//       {
//         breakpoint: 480,
//         settings: {
//           slidesToShow: 1,
//           slidesToScroll: 1,
//           infinite: true,
//           dots: true,
//         }
//       }
//     ]
//   };

//   return (
//     <div>
//       <Head>
//         <title>My Slider App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className="flex flex-col items-center justify-center min-h-screen py-10 bg-gray-100 border">
//         <h1 className="text-4xl font-bold mb-8 mt-[50px] text-center">Featured Vendors</h1>
//         <p className="text-center mb-8">Lorem ipsum, dolor sit amet consectetur adipisicing elit.</p>
//         <div className="w-full max-w-6xl mx-auto">
//           <Slider {...settings}>
//             {[...Array(7)].map((_, index) => (
//               <div key={index}>
//                 <SliderCard />
//               </div>
//             ))}
//           </Slider>
//         </div>
//       </main>
//     </div>
//   );
// }



"use client";
import Head from 'next/head';
import React from "react";
import Slider from 'react-slick';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Images } from '@/constants/constant';
import Popularg from '../Popularg/Popularg';
import SliderCard from '../SliderCard/SliderCard';

function Popular() {
  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 5,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 3000,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        }
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        }
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        }
      }
    ]
  };

  return (
    <div className="px-4 sm:px-6 pt-32 sm:pt-20">
      <Head >
        <title>My Slider App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-2xl sm:text-4xl font-bold text-center font-poppins">Featured Vendors</p>
      <p className="text-md text-center mt-4 mb-8 font-poppins">
        Lorem ipsum, dolor sit amet consectetur corporis doloremque consequatur suscipit.
      </p>
      <main className="flex flex-col items-center bg-indigo-400/50 p-10">
        <div className="w-full max-w-7xl " data-aos="fade-up">
          <Slider {...settings}>
            <div className="px-2">
              <SliderCard/>
            </div>
            <div className="px-2">
              <SliderCard />
            </div>
            <div className="px-2">
              <SliderCard/>
            </div>
            <div className="px-2">
              <SliderCard />
            </div>
            <div className="px-2">
              <SliderCard />
            </div>
            <div className="px-2">
              <SliderCard />
            </div>
          </Slider>
        </div>
      </main>
    </div>
  );
}

export default Popular;
