"use client";
import Head from 'next/head';
import React from "react";
import Slider from 'react-slick';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Images } from '@/constants/constant';
import Popularg from '../Popularg/Popularg';

function Popular() {
  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 5,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 3000,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        }
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        }
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        }
      }
    ]
  };

  return (
    <div className="px-4 sm:px-6 pt-32 sm:pt-20" data-aos="fade-up" data-aos-delay="400">
      <Head >
        <title>My Slider App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-2xl sm:text-4xl font-bold text-center">Popular Searches</p>
      <p className="text-md text-center mt-4 mb-8">
        Lorem ipsum, dolor sit amet consectetur corporis doloremque consequatur suscipit.
      </p>
      <main className="flex flex-col items-center bg-indigo-400/40 p-10">
        <div className="w-full max-w-6xl " data-aos="fade-up">
          <Slider {...settings}>
            <div className="px-2">
              <Popularg name="Bridal Wear" Img={Images.images} />
            </div>
            <div className="px-2">
              <Popularg name="Photographers" Img={Images.images1} />
            </div>
            <div className="px-2">
              <Popularg name="Flowers" Img={Images.images2} />
            </div>
            <div className="px-2">
              <Popularg name="Hotels" Img={Images.images3} />
            </div>
            <div className="px-2">
              <Popularg name="Gateway" Img={Images.images5} />
            </div>
            <div className="px-2">
              <Popularg name="Music Bands" Img={Images.images6} />
            </div>
          </Slider>
        </div>
      </main>
    </div>
  );
}

export default Popular;
