"use client";
import Head from 'next/head';
import React from "react";
import Slider from 'react-slick';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import PopularVenus from '../popularVenus/PopularVenus';
import { Images } from '@/constants/constant';

function Line1() {
  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 5,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 3000,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        }
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        }
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: false,
        }
      }
    ]
  };

  return (
    <div className="px-4 sm:px-6 pt-32 sm:pt-20 font-cookie">
      <Head >
        <title>My Slider App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-2xl sm:text-4xl font-bold text-center">Popular Venues</p>
      <p className="text-md mt-4 text-center mb-8">
        Lorem ipsum, dolor sit amet consectetur corporis doloremque consequatur suscipit.
      </p>
      <main className="flex flex-col items-center bg-indigo-400/30 py-10">
        <div className="w-full max-w-6xl px-4 sm:px-6" data-aos="fade-down" data-aos-delay="400">
          <Slider {...settings} className="mt-8 space-y-8">
            <div className="px-2 ">
              <PopularVenus name="Hotel Luxury Way" Img={Images.images} />
            </div>
            <div className="px-2 ">
              <PopularVenus name="Sea Side Hotel" Img={Images.images1} />
            </div>
            <div className="px-2 ">
              <PopularVenus name="Beach Hotel" Img={Images.images2} />
            </div>
            <div className="px-2 ">
              <PopularVenus name="Movenpick Hotal" Img={Images.images3} />
            </div>
            <div className="px-2 ">
              <PopularVenus name="Gateway Hotel" Img={Images.images5} />
            </div>
            <div className="px-2 ">
              <PopularVenus name="Night Hotel" Img={Images.images6} />
            </div>
          </Slider>
        </div>
      </main>
    </div>
  );
}

export default Line1;
